initial check-in
vscjavaci/headless-debugger pull request #1
Opened 2017-08-02 06:30 UTC by andxu

2017-08-02 06:40 UTC, akaroml requested changes

2017-08-02 06:40 UTC, akaroml commented on src/main/java/org/eclipse/jdt/ls/debug/DebugEvent.java
> +/*******************************************************************************
Please avoid checking in copies. Let's use symbolic link to reference source code from original repository.

2017-08-02 06:40 UTC, akaroml commented on build.gradle
> +     main.java.srcDirs = ['src/main/java']
Use symbolic link.

2017-08-02 07:33 UTC, testforstephen commented on headless-src/test/java/org/eclipse/jdt/ls/debug/DebugUtilityTest.java
> +        mockOptions.setValue("-cp c:/foo");
"-cp c:/foo" should not be hard code absolute path.

2017-08-02 10:17 UTC, akaroml requested changes
Please get rid of the binaries. These binaries need to be referenced from JDK, MVN Central or build from other projects. Please don't check in these files in source control.

2017-08-03 01:44 UTC, andxu commented
@akaroml the source for jdi is not available in any mvn repo since JDK itself  is not built by MVN. We need the modified version of  language server bin and source on our cloned git, so it is not available in any MVN server.

2017-08-03 04:18 UTC, akaroml commented
Can we reference %java_home%/lib/tools.jar instead of checking in the binary?

2017-08-03 04:18 UTC, akaroml requested changes
Can we reference %java_home%/lib/tools.jar instead of checking in the binary?

2017-08-07 10:03 UTC, akaroml approved these changes
Good job. Thanks.

2017-08-08 02:17 UTC, merged